version: 4
interactionInterval: 5000
hologramItemShow: true
# never, doubleclick, always
formOperate: "doubleclick"
packetSendPerSecondMax: 500
interactionWithResidencePlugin: true
createShopInResidenceOnly: true
opIgnoreResidence: false
snakeDestroyShop: false
hopperActiveInResidenceOnly: true
useCustomItemName: true