name: QuickShopX
main: cn.innc11.QuickShopX.QuickShopXPlugin
version: "1.3.1"
author: innc11
api: ["1.0.0"]
load: POSTWORLD
depend: ["EconomyAPI"]
softdepend: ["Residence"]
website: "https://github.com/innc11/QuickShopX"
description: "&l&eQuickShopX&r, &dMade by innc11, original author WetABQ"